apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: mcp
data:
  POSTGRES_DB: aiagent_db
#  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mcp
type: Opaque
data:
  # Username: postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # Password: aiagent (base64 encoded)
  # To generate: echo -n 'your_password' | base64
  POSTGRES_PASSWORD: YWlhZ2VudA==
